name: Create an Environment

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The Name of the repository to be created'
        required: true
      feImage:
        description: 'The tag of the FE image to be used'
        required: true
      beImage:
        description: 'The tag of the BE image to be used'
        required: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      # with:
        # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform init -backend-config="key=backstage-${{ github.event.inputs.environmentName }}.tfstate"
      working-directory: Terraform
    - name: Terraform FMT
      run: terraform fmt
      working-directory: Terraform
    - name: Terraform Validate
      run: terraform validate
      working-directory: Terraform
    - name: Terraform Apply
      env:
        TF_VAR_feImage: ${{ github.event.inputs.feImage }}
        TF_VAR_beImage: ${{ github.event.inputs.beImage }}
        TF_VAR_environmentUrl: http://${{ github.event.inputs.environmentName }}.example.com
        # HCP_WORKSPACE_ID: ${{ secrets.HCP_WORKSPACE_ID }}
      run: terraform apply -auto-approve
      working-directory: Terraform

    # # Dummy deployment step
    # - name: Deploy FE & BE app
    #   run: |
    #     echo "Deploying FE & BE app"
    #     echo "FE image: ${{ github.event.inputs.feImage }}"
    #     echo "BE image: ${{ github.event.inputs.beImage }}"
    #     echo "FE & BE app deployed"